data = [
    {
      "router": "lot-config",
      "internationalizationCode": "front.parkManagement",
      "children": [
        {
          "router": "lot-info",
          "internationalizationCode": "front.lotInfoConfig",
          "children": [],
          "icon": None,
          "name": "车场信息管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2023-05-16 10:26:02",
          "id": 42,
          "sort": 1,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "map-config",
          "internationalizationCode": "front.lotMapConfig",
          "children": [],
          "icon": None,
          "name": "车场地图管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2023-08-09 11:12:25",
          "id": 590,
          "sort": 2,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "area-config",
          "internationalizationCode": "front.areaConfig",
          "children": [],
          "icon": None,
          "name": "区域管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2023-04-04 10:53:52",
          "id": 48,
          "sort": 3,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "park-relate-area",
          "internationalizationCode": "front.parkRelateArea",
          "children": [],
          "icon": None,
          "name": "车位关联区域",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2023-04-04 10:53:52",
          "id": 50,
          "sort": 4,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "path-plan",
          "internationalizationCode": "front.pathPlan",
          "children": [],
          "icon": None,
          "name": "路线规划",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2023-04-04 10:53:54",
          "id": 88,
          "sort": 6,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "park-light-config",
          "internationalizationCode": "front.parkLightConfig",
          "children": [],
          "icon": None,
          "name": "车位灯方案管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2023-04-04 10:53:56",
          "id": 56,
          "sort": 8,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "park-lamp-scheme",
          "internationalizationCode": "front.parkLampDistributionRecord",
          "children": [],
          "icon": None,
          "name": "车位灯方案下发记录",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2023-04-04 10:53:56",
          "id": 578,
          "sort": 9,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "map-style-manage",
          "internationalizationCode": "front.mapStyleManage",
          "children": [],
          "icon": None,
          "name": "地图样式管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2023-04-04 10:53:58",
          "id": 58,
          "sort": 10,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "device-list",
          "internationalizationCode": "front.deviceList",
          "children": [],
          "icon": None,
          "name": "设备列表",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2024-04-23 18:21:33",
          "id": 597,
          "sort": 12,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "stereoscopic-park",
          "internationalizationCode": "front.stereoscopicPark",
          "children": [],
          "icon": None,
          "name": "立体车位管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2024-01-19 14:44:49",
          "id": 595,
          "sort": 13,
          "parentId": 9,
          "status": 1
        },
        {
          "router": "area-camera-list",
          "internationalizationCode": "front.regionalCameraList",
          "children": [],
          "icon": None,
          "name": "区域设备管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2024-04-01 14:17:47",
          "id": 594,
          "sort": 14,
          "parentId": 9,
          "status": 1
        }
      ],
      "icon": "AppstoreFilled",
      "name": "车场维护",
      "linkWay": 0,
      "menuType": 0,
      "updateTime": "2023-04-02 20:03:19",
      "id": 9,
      "sort": 1,
      "parentId": 0,
      "status": 1
    },
    {
      "router": "data-statistics",
      "internationalizationCode": "front.dataStatistics",
      "children": [],
      "icon": "AppstoreFilled",
      "name": "数据统计",
      "linkWay": 0,
      "menuType": 0,
      "updateTime": "2024-10-30 14:23:09",
      "id": 44,
      "sort": 2,
      "parentId": 0,
      "status": 1
    },
    {
      "router": "find-config",
      "internationalizationCode": "front.findCarConfig",
      "children": [
        {
          "router": "finder-machine-config",
          "internationalizationCode": "front.machineConfig",
          "children": [],
          "icon": None,
          "name": "找车机配置",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-05-01 04:39:48",
          "id": 61,
          "sort": 2,
          "parentId": 51,
          "status": 1
        }
      ],
      "icon": "AppstoreFilled",
      "name": "找车管理",
      "linkWay": 0,
      "menuType": 0,
      "updateTime": "2022-07-26 07:20:04",
      "id": 51,
      "sort": 3,
      "parentId": 0,
      "status": 1
    },
    {
      "router": "guide-config",
      "internationalizationCode": "front.guideConfig",
      "children": [
        {
          "router": "lcd-ad-plan",
          "internationalizationCode": "front.lcdAdPlan",
          "children": [],
          "icon": None,
          "name": "LCD屏广告方案",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-04-19 10:24:49",
          "id": 64,
          "sort": 0,
          "parentId": 59,
          "status": 1
        },
        {
          "router": "lcd-config",
          "internationalizationCode": "front.lcdConfig",
          "children": [],
          "icon": None,
          "name": "LCD屏管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-04-19 10:24:51",
          "id": 63,
          "sort": 2,
          "parentId": 59,
          "status": 1
        },
        {
          "router": "car-screen",
          "internationalizationCode": "front.carScreenCorresponding",
          "children": [],
          "icon": None,
          "name": "车屏对应",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-04-19 10:24:51",
          "id": 62,
          "sort": 3,
          "parentId": 59,
          "status": 1
        }
      ],
      "icon": "AppstoreFilled",
      "name": "引导管理",
      "linkWay": 0,
      "menuType": 0,
      "updateTime": "2022-07-26 07:20:08",
      "id": 59,
      "sort": 4,
      "parentId": 0,
      "status": 1
    },
    {
      "router": "warn-config",
      "internationalizationCode": "front.warnConfig",
      "children": [
        {
          "router": "park-error",
          "internationalizationCode": "front.parkWarnConfig",
          "children": [],
          "icon": None,
          "name": "车位违停告警配置\t",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-05-29 16:31:01",
          "id": 81,
          "sort": 1,
          "parentId": 65,
          "status": 1
        },
        {
          "router": "warn-park-record",
          "internationalizationCode": "front.warnParkRecord",
          "children": [],
          "icon": None,
          "name": "违停告警记录",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-04-11 03:03:51",
          "id": 67,
          "sort": 2,
          "parentId": 65,
          "status": 1
        },
        {
          "router": "special-vehicle-config",
          "internationalizationCode": "front.specialVehicleConfiguration",
          "children": [],
          "icon": None,
          "name": "特殊车辆配置",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-05-24 07:31:42",
          "id": 82,
          "sort": 5,
          "parentId": 65,
          "status": 1
        },
        {
          "router": "park-occupy",
          "internationalizationCode": "front.parkUseWarnConfig",
          "children": [],
          "icon": None,
          "name": "车辆占用告警配置",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-06-01 03:27:35",
          "id": 83,
          "sort": 7,
          "parentId": 65,
          "status": 1
        }
      ],
      "icon": "AppstoreFilled",
      "name": "告警管理",
      "linkWay": 0,
      "menuType": 0,
      "updateTime": "2022-07-26 07:20:14",
      "id": 65,
      "sort": 5,
      "parentId": 0,
      "status": 1
    },
    {
      "router": "system-config",
      "internationalizationCode": "front.systemConfig",
      "children": [
        {
          "router": "user-config",
          "internationalizationCode": "front.userConfig",
          "children": [],
          "icon": "",
          "name": "用户管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-06-30 07:41:50",
          "id": 4,
          "sort": 1,
          "parentId": 3,
          "status": 1
        },
        {
          "router": "menu-config",
          "internationalizationCode": "front.menuConfig",
          "children": [],
          "icon": None,
          "name": "菜单管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-04-20 02:11:49",
          "id": 26,
          "sort": 1,
          "parentId": 3,
          "status": 1
        },
        {
          "router": "role-config",
          "internationalizationCode": "front.roleConfig",
          "children": [],
          "icon": None,
          "name": "角色管理",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-05-19 03:36:14",
          "id": 68,
          "sort": 3,
          "parentId": 3,
          "status": 1
        },
        {
          "router": "lang-config",
          "internationalizationCode": "front.internationalization",
          "children": [],
          "icon": "",
          "name": "国际化",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-06-30 07:41:50",
          "id": 15,
          "sort": 4,
          "parentId": 3,
          "status": 1
        },
        {
          "router": "param-config",
          "internationalizationCode": "front.parameterConfig",
          "children": [],
          "icon": None,
          "name": "参数配置",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-09-07 15:20:45",
          "id": 564,
          "sort": 9,
          "parentId": 3,
          "status": 1
        },
        {
          "router": "tool-list",
          "internationalizationCode": "front.toolList",
          "children": [],
          "icon": None,
          "name": "工具集",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-12-27 16:00:37",
          "id": 537,
          "sort": 10,
          "parentId": 3,
          "status": 1
        }
      ],
      "icon": "AppstoreFilled",
      "name": "系统配置",
      "linkWay": 0,
      "menuType": 0,
      "updateTime": "2022-07-26 07:20:18",
      "id": 3,
      "sort": 6,
      "parentId": 0,
      "status": 1
    },
    {
      "router": "customized-features",
      "internationalizationCode": "front.customizedFeatures",
      "children": [
        {
          "router": "group-parking-lights",
          "internationalizationCode": "front.groupParkingLights",
          "children": [],
          "icon": None,
          "name": "车位灯分组",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2024-05-29 13:38:11",
          "id": 676,
          "sort": 1,
          "parentId": 675,
          "status": 1
        }
      ],
      "icon": "AppstoreFilled",
      "name": "定制功能",
      "linkWay": 0,
      "menuType": 0,
      "updateTime": "2024-05-16 16:00:20",
      "id": 675,
      "sort": 8,
      "parentId": 0,
      "status": 1
    },
    {
      "router": "log-config",
      "internationalizationCode": "front.logConfig",
      "children": [
        {
          "router": "sign-log",
          "internationalizationCode": "front.signLog",
          "children": [],
          "icon": None,
          "name": "登录日志",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2022-08-26 17:16:18",
          "id": 70,
          "sort": 2,
          "parentId": 562,
          "status": 1
        },
        {
          "router": "operation-log",
          "internationalizationCode": "front.operationLog",
          "children": [],
          "icon": None,
          "name": "操作日志",
          "linkWay": 0,
          "menuType": 0,
          "updateTime": "2024-09-03 17:26:05",
          "id": 679,
          "sort": 3,
          "parentId": 562,
          "status": 1
        }
      ],
      "icon": "AppstoreFilled",
      "name": "日志管理",
      "linkWay": 0,
      "menuType": 0,
      "updateTime": "2022-08-26 17:15:02",
      "id": 562,
      "sort": 9,
      "parentId": 0,
      "status": 1
    }
  ]

if __name__ == '__main__':

    permission_ids = []
    for i in data:
        for n in i["children"]:
            permission_ids.append(n['id'])

    print(permission_ids)
    print(len(permission_ids))
