server:
  host: "192.168.21.130"
  port: 7799

devices_addr:
  channel_camera_ip: "192.168.6.94"
#  lora_node_ip: "192.168.1.11"
#  network_led_ip: "192.168.1.12"
#  parking_camera_ip: "192.168.1.13"

devices_info:
  channel_camera:
    device_id: "SY17711123"
    device_version: "RDD.CSA.S1A.1.0"
  lora_node: ""
  network_led: ""
  parking_camera: ""