server:
  host: "192.168.21.130"

devices_addr:
  channel_camera_ip: "192.168.24.117"
  parking_camera_ip: "192.168.24.118"
  lora_node_ip: "192.168.24.119"
  four_bytes_node_ip: "192.168.24.120"
  network_led_ip: "192.168.24.121"

devices_info:
  channel_camera:
    device_id: "SY17711123"
    device_version: "RDD.CSA.S1A.1.0"

  parking_camera:
    device_type: 0x00  # 协议定义的设备类型
    device_version: 0x0400  # 协议定义的设备版本

  network_led:
    device_type: 0x0C  # DSP类别（网络版LED屏）
    device_version: 0x0400  # 设备版本号

  lora_node: ""
  four_bytes_node: ""